/* Generated By:JJTree: Do not edit this line. ASTMyOtherID.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMyOtherID extends SimpleNode {
  public ASTMyOtherID(int id) {
    super(id);
  }

  public ASTMyOtherID(Example4 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Example4Visitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d6b8a8f9a070c5055a8dda387e4dd8ea (do not edit this line) */
