/* Generated By:JavaCC: Do not edit this line. Example4Visitor.java Version 7.0.11 */
public interface Example4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=77ffbea321b0f7477cc4dc7c932d0f38 (do not edit this line) */
