/* Generated By:JavaCC: Do not edit this line. Example4DefaultVisitor.java Version 7.0.11 */
public class Example4DefaultVisitor implements Example4Visitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMult node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMyOtherID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInteger node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=a34ff40e3175ac770284ac4fc1c3d2ca (do not edit this line) */
