/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Example3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95cbf944fa6721b91194242464c2ae4c (do not edit this line) */
