/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Example3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b85cd7da56875d92335412a636d74c28 (do not edit this line) */
