/* Generated By:JJTree: Do not edit this line. ASTMyID.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMyID extends SimpleNode {
  public ASTMyID(int id) {
    super(id);
  }

  public ASTMyID(Example3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf3df569b47c4836ab45063633d8aa62 (do not edit this line) */
