/* Generated By:JavaCC: Do not edit this line. Example3TreeConstants.java Version 7.0.11 */
public interface Example3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=0ac5d745ff8c431bc649137aed2c6020 (do not edit this line) */
