/* Generated By:JavaCC: Do not edit this line. IdListConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IdListConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Id = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<Id>",
  };

}
