/* Generated By:JJTree: Do not edit this line. ASTMyID.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMyID extends SimpleNode {
  public ASTMyID(int id) {
    super(id);
  }

  public ASTMyID(Example2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f64f1af8e6eb6b4830379dd2a47e02e (do not edit this line) */
