/* Generated By:JavaCC: Do not edit this line. Example2TreeConstants.java Version 7.0.11 */
public interface Example2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=8f29332e39a19e48ed524d39cff173d8 (do not edit this line) */
